### final

In [32]:
### 0. import
import psycopg2
import numpy  as np
import pandas as pd
from datetime import datetime

# display option (float 자리수)
pd.options.display.float_format = lambda x: f'{x:.6f}'


### 1. 데이터 가져오기
# AWS DW Connect
aws_conn = psycopg2.connect(
    host = 'redshift-cluster-1.ctvbwnnvbdkl.ap-northeast-2.redshift.amazonaws.com',
    port = 5439,
    dbname = 'dev',
    user = 'awsuser',
    password = 'cremaoAdmin1234qwer!!'
)
aws_cursor = aws_conn.cursor()

# pnu별 상업용 부동산 수
sql = '''
select count(mgm_bldrgst_pk), sigungu_cd||bjdong_cd||case when plat_gb_cd = '1' then '2' else '1' end||bun||ji as pnu
  from m1.bld_rgst
 where main_purps_cd_nm not in 
	(
	select distinct main_purps_cd_nm
	from m1.bld_rgst
	where main_purps_cd_nm like '%주택%'
	)
  and base_ym = '202209'
group by sigungu_cd||bjdong_cd||case when plat_gb_cd = '1' then '2' else '1' end||bun||ji
'''
aws_cursor.execute(sql)
aws_conn.commit()
rows = aws_cursor.fetchall()

df_bld_rgst = pd.DataFrame(rows)
df_bld_rgst.columns = ['bld_count','pnu_x']
df_bld_rgst['bun'] = df_bld_rgst['pnu_x'].str[:15] # 15: 본번까지 구분해서 병합
df_bld_rgst['emd_cd'] = df_bld_rgst['pnu_x'].str[:8] + '00'

# pnu별 유동인구 
sql = '''
select substring(bd_mgt_sn, 0, 20) as pnu, avg(f_tot)
  from m1.kt_bldg_xy_info
 where base_ym = '202209'
 group by substring(bd_mgt_sn, 0, 20)
'''
aws_cursor.execute(sql)
aws_conn.commit()
rows = aws_cursor.fetchall()

df_f_tot = pd.DataFrame(rows)
df_f_tot.columns = ['pnu','f_tot']
df_f_tot['bun'] = df_f_tot['pnu'].str[:15]


# 데이터 프레임 병합
df = pd.merge(df_bld_rgst, df_f_tot, on='bun', how='left')

# 인구가 0명, null인 지역 제외
df = df[~df['pnu'].isnull()]

# 상업용 부동산 수 / 유동인구
df['commercial_per_population'] = (df['bld_count'] / df['f_tot'])

# inf 값 제거후 컬럼 정리
df = df[~(df['commercial_per_population']==np.inf)]
df = df[['pnu','emd_cd','commercial_per_population']]
df['base_ym'] = datetime.today().strftime("%Y%m")

In [33]:
df_bld_rgst

         bld_count                pnu_x              bun      emd_cd
0                1  1111010100100030100  111101010010003  1111010100
1                1  1111010100100060003  111101010010006  1111010100
2                1  1111010100100150005  111101010010015  1111010100
3                1  1111010100100150046  111101010010015  1111010100
4                1  1111010100100300007  111101010010030  1111010100
...            ...                  ...              ...         ...
2047183          1  5013032026115240006  501303202611524  5013032000
2047184          1  5013032026115240011  501303202611524  5013032000
2047185          2  5013032026115410004  501303202611541  5013032000
2047186          1  5013032026115710001  501303202611571  5013032000
2047187          1  5013032026118800000  501303202611880  5013032000

[2047188 rows x 4 columns]

In [38]:
df_f_tot

                         pnu          f_tot              bun
0        1111010100100010000 2198691.000000  111101010010001
1        1111010100100030065 3988060.000000  111101010010003
2        1111010100100060003 1444137.000000  111101010010006
3        1111010100100150005 2198691.000000  111101010010015
4        1111010100100150009 2198691.000000  111101010010015
...                      ...            ...              ...
1339480  5013032026108430003   97462.000000  501303202610843
1339481  5013032026113380001   37262.000000  501303202611338
1339482  5013032026114350009   28705.000000  501303202611435
1339483  5013032026114810001   37262.000000  501303202611481
1339484  5013032026115240006   97462.000000  501303202611524

[1339485 rows x 3 columns]

In [37]:
df

                         pnu      emd_cd  commercial_per_population base_ym
0        1111010100100030065  1111010100                   0.000000  202211
1        1111010100100060003  1111010100                   0.000001  202211
2        1111010100100150005  1111010100                   0.000000  202211
3        1111010100100150009  1111010100                   0.000000  202211
4        1111010100100150056  1111010100                   0.000000  202211
...                      ...         ...                        ...     ...
9734808  5013032026115240008  5013032000                   0.000010  202211
9734809  5013032026115240006  5013032000                   0.000010  202211
9734810  5013032026115240001  5013032000                   0.000010  202211
9734811  5013032026115240008  5013032000                   0.000010  202211
9734812  5013032026115240006  5013032000                   0.000010  202211

[8777671 rows x 4 columns]

In [41]:
df['commercial_per_population'].median()

2.8820295944090933e-07

In [39]:
### 2. DB INSERT
import datetime

table = 'm2.datadam_commercial_per_population'

# execute_mogrify
def execute_mogrify(conn, df, table, val):
    # Create a list of tuples from the dataframe values
    tuples = [tuple(x) for x in df.to_numpy()]
    # Comma-separated dataframe columns
    cols = ','.join(list(df.columns))
    # SQL query to execute
    cursor = conn.cursor()
    values = [cursor.mogrify(val, tup).decode('utf8') for tup in
              tuples]
    query = "INSERT INTO %s(%s) VALUES " % (table, cols) + ",".join(values)

    try:
        cursor.execute(query, tuples)
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        conn.rollback()
        cursor.close()
        return 1
    cursor.close()

# values 설정
val = '(' + ('%s,' * len(df.columns))[:-1] + ')'

# insert
for j in range(0, len(df), 10000):

    # DB Connect
    conn = psycopg2.connect(
        host='redshift-cluster-1.ctvbwnnvbdkl.ap-northeast-2.redshift.amazonaws.com',
        port=5439,
        dbname='dev',
        user='awsuser',
        password='cremaoAdmin1234qwer!!'
    )

    # 10000개 단위로 나누기
    tmp = df[j:j + 10000]

    # insert
    execute_mogrify(conn, tmp, table, val)
    print(datetime.datetime.now(), ' : ', j)
    tmp = pd.DataFrame()

# row count
print(len(df))

2022-11-03 17:58:27.596933  :  0
2022-11-03 17:58:30.516045  :  10000
2022-11-03 17:58:32.801245  :  20000
2022-11-03 17:58:34.745037  :  30000
2022-11-03 17:58:36.975171  :  40000
2022-11-03 17:58:39.353799  :  50000
2022-11-03 17:58:41.864627  :  60000
2022-11-03 17:58:44.082782  :  70000
2022-11-03 17:58:49.196409  :  80000
2022-11-03 17:58:53.269273  :  90000
2022-11-03 17:59:01.542814  :  100000
2022-11-03 17:59:10.506096  :  110000
2022-11-03 17:59:16.758632  :  120000
2022-11-03 17:59:33.648532  :  130000
2022-11-03 17:59:36.691538  :  140000
2022-11-03 17:59:39.126525  :  150000
2022-11-03 17:59:41.640692  :  160000
2022-11-03 17:59:43.949140  :  170000
2022-11-03 17:59:46.018814  :  180000
2022-11-03 17:59:50.053839  :  190000
2022-11-03 17:59:55.956637  :  200000
2022-11-03 17:59:58.991098  :  210000
2022-11-03 18:00:01.018952  :  220000
2022-11-03 18:00:06.551956  :  230000
2022-11-03 18:00:11.884712  :  240000
2022-11-03 18:00:14.051411  :  250000
2022-11-03 18:00:18.980303  :  260000
2022-11-03 18:00:24.567955  :  270000
2022-11-03 18:00:28.909333  :  280000
2022-11-03 18:00:31.345050  :  290000
2022-11-03 18:00:33.546902  :  300000
2022-11-03 18:00:39.130243  :  310000
2022-11-03 18:00:42.716200  :  320000
2022-11-03 18:00:45.107292  :  330000
2022-11-03 18:00:47.687296  :  340000
2022-11-03 18:00:52.757654  :  350000
2022-11-03 18:00:55.638477  :  360000
2022-11-03 18:00:58.186648  :  370000
2022-11-03 18:01:00.878188  :  380000
2022-11-03 18:01:03.027207  :  390000
2022-11-03 18:01:05.202646  :  400000
2022-11-03 18:01:07.600222  :  410000
2022-11-03 18:01:16.351511  :  420000
2022-11-03 18:01:19.098451  :  430000
2022-11-03 18:01:23.528022  :  440000
2022-11-03 18:01:25.731557  :  450000
2022-11-03 18:01:28.786353  :  460000
2022-11-03 18:01:31.423311  :  470000
2022-11-03 18:01:33.668913  :  480000
2022-11-03 18:01:36.256726  :  490000
2022-11-03 18:01:40.578502  :  500000
2022-11-03 18:01:44.742260  :  510000
2022-11-03 18:01:48.832770  :  520000
2022-11-03 18:01:53.961975  :  530000
2022-11-03 18:01:56.135110  :  540000
2022-11-03 18:01:58.288248  :  550000
2022-11-03 18:02:00.234018  :  560000
2022-11-03 18:02:04.424239  :  570000
2022-11-03 18:02:06.483358  :  580000
2022-11-03 18:02:10.855507  :  590000
2022-11-03 18:02:15.267095  :  600000
2022-11-03 18:02:19.512528  :  610000
2022-11-03 18:02:22.134677  :  620000
2022-11-03 18:02:25.546713  :  630000
2022-11-03 18:02:28.348874  :  640000
2022-11-03 18:02:32.073486  :  650000
2022-11-03 18:02:34.603461  :  660000
2022-11-03 18:02:36.673606  :  670000
2022-11-03 18:02:38.704780  :  680000
2022-11-03 18:02:40.897901  :  690000
2022-11-03 18:02:43.384065  :  700000
2022-11-03 18:02:45.929218  :  710000
2022-11-03 18:02:47.916351  :  720000
2022-11-03 18:02:52.998225  :  730000
2022-11-03 18:02:55.155733  :  740000
2022-11-03 18:02:57.093199  :  750000
2022-11-03 18:02:59.667773  :  760000
2022-11-03 18:03:01.889005  :  770000
2022-11-03 18:03:06.272898  :  780000
2022-11-03 18:03:11.101668  :  790000
2022-11-03 18:03:17.124701  :  800000
2022-11-03 18:03:19.144697  :  810000
2022-11-03 18:03:21.155207  :  820000
2022-11-03 18:03:23.237385  :  830000
2022-11-03 18:03:25.311542  :  840000
2022-11-03 18:03:28.120458  :  850000
2022-11-03 18:03:29.976394  :  860000
2022-11-03 18:03:32.148565  :  870000
2022-11-03 18:03:34.165225  :  880000
2022-11-03 18:03:36.391952  :  890000
2022-11-03 18:03:38.545746  :  900000
2022-11-03 18:03:41.895924  :  910000
2022-11-03 18:03:43.987925  :  920000
2022-11-03 18:03:46.243176  :  930000
2022-11-03 18:03:48.077333  :  940000
2022-11-03 18:03:50.259199  :  950000
2022-11-03 18:03:53.537083  :  960000
2022-11-03 18:03:55.571673  :  970000
2022-11-03 18:03:57.622452  :  980000
2022-11-03 18:03:59.668903  :  990000
2022-11-03 18:04:01.743324  :  1000000
2022-11-03 18:04:04.101944  :  1010000
2022-11-03 18:04:07.058231  :  1020000
2022-11-03 18:04:09.754815  :  1030000
2022-11-03 18:04:14.300906  :  1040000
2022-11-03 18:04:16.782726  :  1050000
2022-11-03 18:04:18.923191  :  1060000
2022-11-03 18:04:21.233892  :  1070000
2022-11-03 18:04:23.870758  :  1080000
2022-11-03 18:04:26.990144  :  1090000
2022-11-03 18:04:29.135468  :  1100000
2022-11-03 18:04:31.152497  :  1110000
2022-11-03 18:04:33.250460  :  1120000
2022-11-03 18:04:35.303570  :  1130000
2022-11-03 18:04:37.985763  :  1140000
2022-11-03 18:04:40.304539  :  1150000
2022-11-03 18:04:43.281741  :  1160000
2022-11-03 18:04:45.321158  :  1170000
2022-11-03 18:04:47.567631  :  1180000
2022-11-03 18:04:49.904521  :  1190000
2022-11-03 18:04:52.203175  :  1200000
2022-11-03 18:04:55.298657  :  1210000
2022-11-03 18:04:57.473594  :  1220000
2022-11-03 18:04:59.445705  :  1230000
2022-11-03 18:05:01.485383  :  1240000
2022-11-03 18:05:06.762431  :  1250000
2022-11-03 18:05:09.215474  :  1260000
2022-11-03 18:05:11.770555  :  1270000
2022-11-03 18:05:13.775049  :  1280000
2022-11-03 18:05:15.876096  :  1290000
2022-11-03 18:05:18.176215  :  1300000
2022-11-03 18:05:20.268790  :  1310000
2022-11-03 18:05:23.945507  :  1320000
2022-11-03 18:05:27.123044  :  1330000
2022-11-03 18:05:32.263666  :  1340000
2022-11-03 18:05:34.302759  :  1350000
2022-11-03 18:05:37.908238  :  1360000
2022-11-03 18:05:39.868417  :  1370000
2022-11-03 18:05:42.007093  :  1380000
2022-11-03 18:05:44.222281  :  1390000
2022-11-03 18:05:46.409811  :  1400000
2022-11-03 18:05:50.212897  :  1410000
2022-11-03 18:05:56.580539  :  1420000
2022-11-03 18:05:59.925878  :  1430000
2022-11-03 18:06:05.327831  :  1440000
2022-11-03 18:06:09.785061  :  1450000
2022-11-03 18:06:13.365149  :  1460000
2022-11-03 18:06:15.502884  :  1470000
2022-11-03 18:06:17.649813  :  1480000
2022-11-03 18:06:19.639267  :  1490000
2022-11-03 18:06:21.952191  :  1500000
2022-11-03 18:06:24.159257  :  1510000
2022-11-03 18:06:27.496342  :  1520000
2022-11-03 18:06:32.440701  :  1530000
2022-11-03 18:06:35.841312  :  1540000
2022-11-03 18:06:43.990402  :  1550000
2022-11-03 18:06:49.898631  :  1560000
2022-11-03 18:06:51.913284  :  1570000
2022-11-03 18:06:54.175978  :  1580000
2022-11-03 18:07:03.558058  :  1590000
2022-11-03 18:07:22.326468  :  1600000
2022-11-03 18:07:24.187375  :  1610000
2022-11-03 18:07:26.304850  :  1620000
2022-11-03 18:07:29.429285  :  1630000
2022-11-03 18:07:31.824586  :  1640000
2022-11-03 18:07:35.404090  :  1650000
2022-11-03 18:07:37.865369  :  1660000
2022-11-03 18:07:39.813944  :  1670000
2022-11-03 18:07:45.054173  :  1680000
2022-11-03 18:07:50.109306  :  1690000
2022-11-03 18:07:52.863921  :  1700000
2022-11-03 18:07:54.823961  :  1710000
2022-11-03 18:07:56.996824  :  1720000
2022-11-03 18:07:59.218197  :  1730000
2022-11-03 18:08:03.492768  :  1740000
2022-11-03 18:08:07.783137  :  1750000
2022-11-03 18:08:09.726711  :  1760000
2022-11-03 18:08:11.660945  :  1770000
2022-11-03 18:08:16.504730  :  1780000
2022-11-03 18:08:18.461446  :  1790000
2022-11-03 18:08:22.794108  :  1800000
2022-11-03 18:08:24.844405  :  1810000
2022-11-03 18:08:27.776083  :  1820000
2022-11-03 18:08:30.005281  :  1830000
2022-11-03 18:08:36.188672  :  1840000
2022-11-03 18:08:40.592474  :  1850000
2022-11-03 18:08:46.691001  :  1860000
2022-11-03 18:08:55.292965  :  1870000
2022-11-03 18:08:58.559870  :  1880000
2022-11-03 18:09:01.885683  :  1890000
2022-11-03 18:09:09.200251  :  1900000
2022-11-03 18:09:16.265022  :  1910000
2022-11-03 18:09:18.762299  :  1920000
2022-11-03 18:09:21.635910  :  1930000
2022-11-03 18:09:26.612602  :  1940000
2022-11-03 18:09:30.675177  :  1950000
2022-11-03 18:09:32.902526  :  1960000
2022-11-03 18:09:35.553703  :  1970000
2022-11-03 18:09:39.425269  :  1980000
2022-11-03 18:09:41.459831  :  1990000
2022-11-03 18:09:43.322890  :  2000000
2022-11-03 18:09:45.522560  :  2010000
2022-11-03 18:09:47.856217  :  2020000
2022-11-03 18:09:54.782273  :  2030000
2022-11-03 18:09:57.843209  :  2040000
2022-11-03 18:10:01.349534  :  2050000
2022-11-03 18:10:06.034642  :  2060000
2022-11-03 18:10:08.679154  :  2070000
2022-11-03 18:10:11.257705  :  2080000
2022-11-03 18:10:13.389298  :  2090000
2022-11-03 18:10:21.124227  :  2100000
2022-11-03 18:10:24.202525  :  2110000
2022-11-03 18:10:28.718492  :  2120000
2022-11-03 18:10:30.788248  :  2130000
2022-11-03 18:10:32.696394  :  2140000
2022-11-03 18:10:35.071195  :  2150000
2022-11-03 18:10:38.053502  :  2160000
2022-11-03 18:10:40.191919  :  2170000
2022-11-03 18:10:49.142768  :  2180000
2022-11-03 18:10:54.015924  :  2190000
2022-11-03 18:10:56.426045  :  2200000
2022-11-03 18:11:01.770808  :  2210000
2022-11-03 18:11:04.111286  :  2220000
2022-11-03 18:11:10.960365  :  2230000
2022-11-03 18:11:17.281215  :  2240000
2022-11-03 18:11:19.550758  :  2250000
2022-11-03 18:11:21.676188  :  2260000
2022-11-03 18:11:24.986989  :  2270000
2022-11-03 18:11:27.525428  :  2280000
2022-11-03 18:11:29.236362  :  2290000
2022-11-03 18:11:31.323100  :  2300000
2022-11-03 18:11:36.123106  :  2310000
2022-11-03 18:11:37.984442  :  2320000
2022-11-03 18:11:41.409258  :  2330000
2022-11-03 18:11:43.354986  :  2340000
2022-11-03 18:11:46.600321  :  2350000
2022-11-03 18:11:49.594094  :  2360000
2022-11-03 18:11:51.497888  :  2370000
2022-11-03 18:11:53.435933  :  2380000
2022-11-03 18:11:55.651719  :  2390000
2022-11-03 18:11:59.726501  :  2400000
2022-11-03 18:12:03.019248  :  2410000
2022-11-03 18:12:05.806372  :  2420000
2022-11-03 18:12:08.956505  :  2430000
2022-11-03 18:12:10.905081  :  2440000
2022-11-03 18:12:13.498683  :  2450000
2022-11-03 18:12:16.740853  :  2460000
2022-11-03 18:12:24.644634  :  2470000
2022-11-03 18:12:27.373290  :  2480000
2022-11-03 18:12:30.685830  :  2490000
2022-11-03 18:12:33.355620  :  2500000
2022-11-03 18:12:35.429695  :  2510000
2022-11-03 18:12:37.287821  :  2520000
2022-11-03 18:12:39.660163  :  2530000
2022-11-03 18:12:43.883649  :  2540000
2022-11-03 18:12:47.081789  :  2550000
2022-11-03 18:12:51.149522  :  2560000
2022-11-03 18:12:53.132786  :  2570000
2022-11-03 18:12:56.676909  :  2580000
2022-11-03 18:12:58.665870  :  2590000
2022-11-03 18:13:01.766027  :  2600000
2022-11-03 18:13:04.905264  :  2610000
2022-11-03 18:13:07.142515  :  2620000
2022-11-03 18:13:09.732337  :  2630000
2022-11-03 18:13:11.815475  :  2640000
2022-11-03 18:13:13.953285  :  2650000
2022-11-03 18:13:16.772722  :  2660000
2022-11-03 18:13:19.990681  :  2670000
2022-11-03 18:13:24.533369  :  2680000
2022-11-03 18:13:28.294586  :  2690000
2022-11-03 18:13:32.157550  :  2700000
2022-11-03 18:13:39.279178  :  2710000
2022-11-03 18:13:42.225862  :  2720000
2022-11-03 18:13:44.943226  :  2730000
2022-11-03 18:13:47.272317  :  2740000
2022-11-03 18:13:49.323678  :  2750000
2022-11-03 18:13:51.864546  :  2760000
2022-11-03 18:13:54.441172  :  2770000
2022-11-03 18:13:57.643446  :  2780000
2022-11-03 18:13:59.751266  :  2790000
2022-11-03 18:14:01.948556  :  2800000
2022-11-03 18:14:04.260425  :  2810000
2022-11-03 18:14:07.106477  :  2820000
2022-11-03 18:14:10.547787  :  2830000
2022-11-03 18:14:12.422964  :  2840000
2022-11-03 18:14:15.314010  :  2850000
2022-11-03 18:14:18.425854  :  2860000
2022-11-03 18:14:21.572382  :  2870000
2022-11-03 18:14:23.474887  :  2880000
2022-11-03 18:14:26.820641  :  2890000
2022-11-03 18:14:38.619731  :  2900000
2022-11-03 18:14:40.317088  :  2910000
2022-11-03 18:14:42.464313  :  2920000
2022-11-03 18:14:44.774311  :  2930000
2022-11-03 18:14:49.546671  :  2940000
2022-11-03 18:14:54.281553  :  2950000
2022-11-03 18:14:58.721723  :  2960000
2022-11-03 18:15:00.846373  :  2970000
2022-11-03 18:15:06.739073  :  2980000
2022-11-03 18:15:08.488603  :  2990000
2022-11-03 18:15:10.600267  :  3000000
2022-11-03 18:15:14.261106  :  3010000
2022-11-03 18:15:17.088486  :  3020000
2022-11-03 18:15:21.824218  :  3030000
2022-11-03 18:15:25.366813  :  3040000
2022-11-03 18:15:27.566357  :  3050000
2022-11-03 18:15:32.431043  :  3060000
2022-11-03 18:15:34.787170  :  3070000
2022-11-03 18:15:38.060799  :  3080000
2022-11-03 18:15:40.747954  :  3090000
2022-11-03 18:15:42.407187  :  3100000
2022-11-03 18:15:45.393883  :  3110000
2022-11-03 18:15:54.330133  :  3120000
2022-11-03 18:15:56.816299  :  3130000
2022-11-03 18:16:01.573814  :  3140000
2022-11-03 18:16:04.496880  :  3150000
2022-11-03 18:16:06.235570  :  3160000
2022-11-03 18:16:09.020531  :  3170000
2022-11-03 18:16:11.885659  :  3180000
2022-11-03 18:16:14.188617  :  3190000
2022-11-03 18:16:21.539146  :  3200000
2022-11-03 18:16:25.678658  :  3210000
2022-11-03 18:16:28.837612  :  3220000
2022-11-03 18:16:31.355391  :  3230000
2022-11-03 18:16:37.955919  :  3240000
2022-11-03 18:16:46.626808  :  3250000
2022-11-03 18:16:52.042688  :  3260000
2022-11-03 18:16:53.843329  :  3270000
2022-11-03 18:16:56.641918  :  3280000
2022-11-03 18:16:59.368517  :  3290000
2022-11-03 18:17:04.775579  :  3300000
2022-11-03 18:17:09.569363  :  3310000
2022-11-03 18:17:11.998172  :  3320000
2022-11-03 18:17:15.883277  :  3330000
2022-11-03 18:17:17.953850  :  3340000
2022-11-03 18:17:20.390263  :  3350000
2022-11-03 18:17:23.947153  :  3360000
2022-11-03 18:17:27.224025  :  3370000
2022-11-03 18:17:31.538132  :  3380000
2022-11-03 18:17:35.096198  :  3390000
2022-11-03 18:17:37.522259  :  3400000
2022-11-03 18:17:39.848876  :  3410000
2022-11-03 18:17:42.775799  :  3420000
2022-11-03 18:17:44.709081  :  3430000
2022-11-03 18:17:47.886477  :  3440000
2022-11-03 18:17:50.950498  :  3450000
2022-11-03 18:17:53.220068  :  3460000
2022-11-03 18:17:55.470229  :  3470000
2022-11-03 18:17:57.562607  :  3480000
2022-11-03 18:18:03.387213  :  3490000
2022-11-03 18:18:06.512645  :  3500000
2022-11-03 18:18:08.621659  :  3510000
2022-11-03 18:18:11.284048  :  3520000
2022-11-03 18:18:13.152865  :  3530000
2022-11-03 18:18:14.955313  :  3540000
2022-11-03 18:18:18.892842  :  3550000
2022-11-03 18:18:21.976103  :  3560000
2022-11-03 18:18:25.754310  :  3570000
2022-11-03 18:18:28.274744  :  3580000
2022-11-03 18:18:31.683065  :  3590000
2022-11-03 18:18:33.977448  :  3600000
2022-11-03 18:18:42.287579  :  3610000
2022-11-03 18:18:44.968213  :  3620000
2022-11-03 18:18:47.193458  :  3630000
2022-11-03 18:18:49.074269  :  3640000
2022-11-03 18:18:53.765425  :  3650000
2022-11-03 18:18:55.691464  :  3660000
2022-11-03 18:19:00.785344  :  3670000
2022-11-03 18:19:06.941777  :  3680000
2022-11-03 18:19:11.514200  :  3690000
2022-11-03 18:19:13.595375  :  3700000
2022-11-03 18:19:16.065061  :  3710000
2022-11-03 18:19:18.521005  :  3720000
2022-11-03 18:19:25.532342  :  3730000
2022-11-03 18:19:27.630770  :  3740000
2022-11-03 18:19:30.090368  :  3750000
2022-11-03 18:19:34.392469  :  3760000
2022-11-03 18:19:40.104283  :  3770000
2022-11-03 18:19:41.828998  :  3780000
2022-11-03 18:19:45.209050  :  3790000
2022-11-03 18:19:51.046929  :  3800000
2022-11-03 18:19:53.603961  :  3810000
2022-11-03 18:19:57.385464  :  3820000
2022-11-03 18:20:04.930842  :  3830000
2022-11-03 18:20:07.759659  :  3840000
2022-11-03 18:20:09.875446  :  3850000
2022-11-03 18:20:12.049225  :  3860000
2022-11-03 18:20:14.244040  :  3870000
2022-11-03 18:20:15.773674  :  3880000
2022-11-03 18:20:17.888919  :  3890000
2022-11-03 18:20:22.731919  :  3900000
2022-11-03 18:20:25.314503  :  3910000
2022-11-03 18:20:28.398260  :  3920000
2022-11-03 18:20:30.618933  :  3930000
2022-11-03 18:20:34.310412  :  3940000
2022-11-03 18:20:36.087133  :  3950000
2022-11-03 18:20:38.315978  :  3960000
2022-11-03 18:20:40.348335  :  3970000
2022-11-03 18:20:42.174929  :  3980000
2022-11-03 18:20:46.579970  :  3990000
2022-11-03 18:20:48.579106  :  4000000
2022-11-03 18:20:50.754237  :  4010000
2022-11-03 18:20:52.890022  :  4020000
2022-11-03 18:20:55.839239  :  4030000
2022-11-03 18:21:00.699232  :  4040000
2022-11-03 18:21:03.617342  :  4050000
2022-11-03 18:21:05.430267  :  4060000
2022-11-03 18:21:07.615760  :  4070000
2022-11-03 18:21:13.420134  :  4080000
2022-11-03 18:21:16.266921  :  4090000
2022-11-03 18:21:18.058670  :  4100000
2022-11-03 18:21:22.840805  :  4110000
2022-11-03 18:21:26.845140  :  4120000
2022-11-03 18:21:31.590726  :  4130000
2022-11-03 18:21:35.846148  :  4140000
2022-11-03 18:21:39.536171  :  4150000
2022-11-03 18:21:43.107586  :  4160000
2022-11-03 18:21:45.553872  :  4170000
2022-11-03 18:21:47.257674  :  4180000
2022-11-03 18:21:49.239329  :  4190000
2022-11-03 18:21:53.029451  :  4200000
2022-11-03 18:21:57.767419  :  4210000
2022-11-03 18:22:00.157063  :  4220000
2022-11-03 18:22:02.173672  :  4230000
2022-11-03 18:22:04.955031  :  4240000
2022-11-03 18:22:09.582718  :  4250000
2022-11-03 18:22:11.789212  :  4260000
2022-11-03 18:22:13.755047  :  4270000
2022-11-03 18:22:15.786243  :  4280000
2022-11-03 18:22:17.519754  :  4290000
2022-11-03 18:22:20.500866  :  4300000
2022-11-03 18:22:23.399486  :  4310000
2022-11-03 18:22:25.610947  :  4320000
2022-11-03 18:22:30.887697  :  4330000
2022-11-03 18:22:33.204917  :  4340000
2022-11-03 18:22:37.394526  :  4350000
2022-11-03 18:22:42.404168  :  4360000
2022-11-03 18:22:44.586810  :  4370000
2022-11-03 18:22:48.650839  :  4380000
2022-11-03 18:22:52.267452  :  4390000
2022-11-03 18:22:54.498701  :  4400000
2022-11-03 18:22:58.259899  :  4410000
2022-11-03 18:23:00.670434  :  4420000
2022-11-03 18:23:08.041950  :  4430000
2022-11-03 18:23:11.201059  :  4440000
2022-11-03 18:23:15.811108  :  4450000
2022-11-03 18:23:18.115707  :  4460000
2022-11-03 18:23:22.342572  :  4470000
2022-11-03 18:23:24.282692  :  4480000
2022-11-03 18:23:27.681094  :  4490000
2022-11-03 18:23:29.908461  :  4500000
2022-11-03 18:23:31.667036  :  4510000
2022-11-03 18:23:33.987265  :  4520000
2022-11-03 18:23:38.949637  :  4530000
2022-11-03 18:23:41.143230  :  4540000
2022-11-03 18:23:43.241234  :  4550000
2022-11-03 18:23:45.097499  :  4560000
2022-11-03 18:23:49.095301  :  4570000
2022-11-03 18:23:53.979174  :  4580000
2022-11-03 18:23:55.979299  :  4590000
2022-11-03 18:23:59.020182  :  4600000
2022-11-03 18:24:02.511128  :  4610000
2022-11-03 18:24:07.007938  :  4620000
2022-11-03 18:24:10.274015  :  4630000
2022-11-03 18:24:12.152744  :  4640000
2022-11-03 18:24:14.361080  :  4650000
2022-11-03 18:24:19.313007  :  4660000
2022-11-03 18:24:21.639787  :  4670000
2022-11-03 18:24:25.303765  :  4680000
2022-11-03 18:25:24.373933  :  4690000
2022-11-03 18:25:26.477270  :  4700000
2022-11-03 18:25:28.504334  :  4710000
2022-11-03 18:25:30.556036  :  4720000
2022-11-03 18:25:33.511231  :  4730000
2022-11-03 18:25:35.804610  :  4740000
2022-11-03 18:25:37.530209  :  4750000
2022-11-03 18:25:41.302927  :  4760000
2022-11-03 18:25:43.053431  :  4770000
2022-11-03 18:25:49.174300  :  4780000
2022-11-03 18:25:52.595756  :  4790000
2022-11-03 18:25:58.811500  :  4800000
2022-11-03 18:26:01.305752  :  4810000
2022-11-03 18:26:04.775336  :  4820000
2022-11-03 18:26:06.863704  :  4830000
2022-11-03 18:26:11.382708  :  4840000
2022-11-03 18:26:16.792132  :  4850000
2022-11-03 18:26:21.004696  :  4860000
2022-11-03 18:26:24.908638  :  4870000
2022-11-03 18:26:30.382219  :  4880000
2022-11-03 18:26:32.573478  :  4890000
2022-11-03 18:26:36.239761  :  4900000
2022-11-03 18:26:37.786219  :  4910000
2022-11-03 18:26:39.774109  :  4920000
2022-11-03 18:26:43.859233  :  4930000
2022-11-03 18:26:46.221177  :  4940000
2022-11-03 18:26:47.909904  :  4950000
2022-11-03 18:26:50.129364  :  4960000
2022-11-03 18:26:52.248630  :  4970000
2022-11-03 18:26:56.545326  :  4980000
2022-11-03 18:26:58.531612  :  4990000
2022-11-03 18:27:03.896692  :  5000000
2022-11-03 18:27:06.465014  :  5010000
2022-11-03 18:27:08.744095  :  5020000
2022-11-03 18:27:10.443808  :  5030000
2022-11-03 18:27:15.091597  :  5040000
2022-11-03 18:27:17.298340  :  5050000
2022-11-03 18:27:19.909762  :  5060000
2022-11-03 18:27:21.709695  :  5070000
2022-11-03 18:27:26.338627  :  5080000
2022-11-03 18:27:28.927938  :  5090000
2022-11-03 18:27:30.898029  :  5100000
2022-11-03 18:27:35.285512  :  5110000
2022-11-03 18:27:37.774711  :  5120000
2022-11-03 18:27:42.026519  :  5130000
2022-11-03 18:27:45.727274  :  5140000

In [83]:
df.describe()

       commercial_per_population
count              462282.000000
mean                    0.000857
std                     0.032387
min                     0.000000
25%                     0.000007
50%                     0.000015
75%                     0.000057
max                    18.000000

###### ver1 (법정동 단위)

In [38]:
### 0. import
import psycopg2
import numpy  as np
import pandas as pd
from datetime import datetime

# display option (float 자리수)
pd.options.display.float_format = lambda x: f'{x:.6f}'


### 1. 데이터 가져오기
# AWS DW Connect
aws_conn = psycopg2.connect(
    host = 'redshift-cluster-1.ctvbwnnvbdkl.ap-northeast-2.redshift.amazonaws.com',
    port = 5439,
    dbname = 'dev',
    user = 'awsuser',
    password = 'cremaoAdmin1234qwer!!'
)
aws_cursor = aws_conn.cursor()

# 법정동별 상가 면적
sql = '''
select sigungu_cd||bjdong_cd as pnu, count(mgm_bldrgst_pk) as total_count
  from m1.bld_rgst
 where main_purps_cd_nm not in 
    (
    select distinct main_purps_cd_nm
    from m1.bld_rgst
    where main_purps_cd_nm like '%주택%'
    )
group by sigungu_cd||bjdong_cd
'''
aws_cursor.execute(sql)
aws_conn.commit()
rows = aws_cursor.fetchall()

df_bld_rgst = pd.DataFrame(rows)
df_bld_rgst.columns = ['emd_cd','total_count']

# 법정동별 유동인구 
sql = '''
    select substring (pnu, 0, 11), sum(f_tot)
      from m2.cremao_land_floating_population
     group by substring (pnu, 0, 11)
'''
aws_cursor.execute(sql)
aws_conn.commit()
rows = aws_cursor.fetchall()

df_f_tot = pd.DataFrame(rows)
df_f_tot.columns = ['emd_cd','f_tot']
df_f_tot = df_f_tot[~df_f_tot['f_tot'].isnull()].reset_index(drop=True)

# 데이터 프레임 병합
df = pd.merge(df_f_tot, df_bld_rgst, on='emd_cd', how='left')

# 인구가 0명, null인 지역 제외
df = df[~df['total_count'].isnull()]

# 상가면적 / 거주인구
df['commercial_per_population'] = (df['total_count'] / df['f_tot'])
df = df[['emd_cd','commercial_per_population']]
df['base_ym'] = datetime.today().strftime("%Y%m")


### 2. DB INSERT
import datetime

table = 'm2.datadam_commercial_per_population'

# execute_mogrify
def execute_mogrify(conn, df, table, val):
    # Create a list of tuples from the dataframe values
    tuples = [tuple(x) for x in df.to_numpy()]
    # Comma-separated dataframe columns
    cols = ','.join(list(df.columns))
    # SQL query to execute
    cursor = conn.cursor()
     # drop & create
    cursor.execute(
    """
    drop table if exists m2.datadam_commercial_per_population;
    create table m2.datadam_commercial_per_population (    
    emd_cd varchar(10)
    , commercial_per_population double precision
    , base_ym varchar(6)
    )
    distkey(emd_cd)
    compound sortkey(base_ym);
    commit;
    """
    )
    values = [cursor.mogrify(val, tup).decode('utf8') for tup in
              tuples]
    query = "INSERT INTO %s(%s) VALUES " % (table, cols) + ",".join(values)

    try:
        cursor.execute(query, tuples)
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        conn.rollback()
        cursor.close()
        return 1
    cursor.close()

# values 설정
val = '(' + ('%s,' * len(df.columns))[:-1] + ')'

# insert
for j in range(0, len(df), 10000):

    # DB Connect
    conn = psycopg2.connect(
        host='redshift-cluster-1.ctvbwnnvbdkl.ap-northeast-2.redshift.amazonaws.com',
        port=5439,
        dbname='dev',
        user='awsuser',
        password='cremaoAdmin1234qwer!!'
    )

    # 10000개 단위로 나누기
    tmp = df[j:j + 10000]

    # insert
    execute_mogrify(conn, tmp, table, val)
    print(datetime.datetime.now(), ' : ', j)
    tmp = pd.DataFrame()

# row count
print(len(df))

2022-10-30 18:08:47.688140  :  0
2022-10-30 18:08:50.007249  :  10000
17296

In [37]:
df.describe()

       commercial_per_population
count               17296.000000
mean                    0.051612
std                     0.292162
min                     0.000000
25%                     0.000259
50%                     0.003113
75%                     0.020263
max                    17.100000