### 법정동 변환/수집 (크레마오에서 크롤링)

In [2]:
import time
from tqdm import tqdm
import pandas as pd

import requests
import urllib
from urllib.request import urlopen
from html_table_parser import parser_functions

from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.support.select import Select

In [19]:
df_open = pd.read_excel('./test.xlsx')

In [20]:
df_open

,법정동코드,법정동명,점포명,상세주소
0,4111513400,경기도 수원시 팔달구 매산로1가,AK수원점,경기도 수원시 팔달구 매산로1가 18번지 외 11필지 수원민자역사 제1호
1,4161025900,경기도 광주시 곤지암읍,BGF곤지암포켓점,경기도 광주시 곤지암읍 건업리 148번지
2,4146311800,경기도 용인시 기흥구 보정동,BGF로지스용인점,경기도 용인시 기흥구 보정동 319번지 1층
3,1168010500,서울특별시 강남구 삼성동,BGF사옥점,서울특별시 강남구 삼성동 141-10번지
4,4163025000,경기도 양주시 백석읍,BGF양주포켓점,경기도 양주시 백석읍 복지리 153번지 2층
...,...,...,...,...
16097,1130510400,서울특별시 강북구 우이동,419사거리점,서울특별시 강북구 우이동 72-144번지
16098,1156011000,서울특별시 영등포구 여의도동,63빌딩점,서울특별시 영등포구 여의도동 60번지 하
16099,2817710400,인천광역시 미추홀구 도화동,6공단1호점,인천광역시 미추홀구 도화동 84-5번지
16100,2817700000,인천광역시 남구 도화동,6공단2호점,인천광역시 남구 도화동 53-77번지
16101,4793038000,경상북도 울진군 후포면,7번국도점,경상북도 울진군 후포면 후포리 917-18번지

In [184]:
# 법정동명, 법정동 코드 가져오기
def get_text():
    bcode.append(driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/ul/li').get_attribute('data-bcode'))
    sido    = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/ul/li').get_attribute('data-sido')    # 시도
    sigungu = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/ul/li').get_attribute('data-sigungu') # 군구
    bname   = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/ul/li').get_attribute('data-bname2')  # 법정동
    lgdng_nm_list.append(sido + ' ' + sigungu + ' ' + bname)
    lgdng_full_nm_list.append(driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/ul/li/dl/dd[1]/span/button/span[1]').text)

In [185]:
# 주소 검색
def search():
    miss_index = []
    for i in tqdm(df_open.index):
        searchByName = driver.find_element_by_xpath('//*[@id="region_name"]')                        # 검색창 선택
        searchByName.clear()                                                                         # 기존 입력 삭제
        
        time.sleep(1)
        
        searchByName.send_keys(df_open['주소전체'][i])                                               # 검색어 입력
        click = driver.find_element_by_xpath('//*[@id="searchForm"]/fieldset/div/button[2]').click() # 검색 버튼 클릭
        
        time.sleep(1)
        
        try:
            get_text()                                                                                # 주소 가져오기
            corp_nm.append(df_open['점포명'][i])
        except:
            miss_index.append(i)
            pass

In [186]:
# 기본 틀
driver = webdriver.Chrome('./driver/chromedriver.exe')
driver.get('https://postcode.map.daum.net/search?origin=https%3A%2F%2Fdev.cremao.co.kr&indaum=off&banner=on&ubl=on&mode=transmit&vt=layer&amr=on&amj=on&ani=off&sd=off&fi=on&fc=on&plrg=&plrgt=1.5&hmb=off&heb=off&asea=off&smh=off&zo=on&us=on&msi=10&ahs=off&whas=500&sm=on&a51=off&theme=BODY.bg_FFFFFF-SEARCH.bg_FFFFFF.placeHolder_bbbbbb.bottomLine_858585-LOGO.text_888888.logoTextDividingLine_cccccc&bit=0&sit=0&sgit=0&sbit=0&pit=0&mit=0&lcit=0&zn=Y&fullpath=%2Fmain')

# 주소 수집
bcode = []              # 법정동 코드
corp_nm = []            # 매장명
lgdng_nm_list = []      # 법정동 명
lgdng_full_nm_list = [] # 법정동 전체 주소
search()

driver.close()

# 저장
df = pd.DataFrame({'corp_nm':corp_nm, 'lgdng_nm_list':lgdng_nm_list,'lgdng_full_nm_list':lgdng_full_nm_list,'bcode':bcode})
df.to_excel('./법정동주소.xlsx', index=False)

100%|████████████████████████████████████████████████████████████████████████████████| 429/429 [15:56<00:00,  2.23s/it]

###### 제대로 안 담겼을 때

In [151]:
df = pd.DataFrame({'lgdng_nm_list':lgdng_nm_list,'lgdng_full_nm_list':lgdng_full_nm_list})

In [153]:
corp_nm = pd.DataFrame({'bcode':bcode})

In [132]:
corp_nm = pd.DataFrame({'corp_nm':corp_nm})

In [101]:
lgdng_nm.to_excel('./test.xlsx', index= False)

###### test

In [18]:
driver = webdriver.Chrome('./driver/chromedriver.exe')
driver.get('https://postcode.map.daum.net/search?origin=https%3A%2F%2Fdev.cremao.co.kr&indaum=off&banner=on&ubl=on&mode=transmit&vt=layer&amr=on&amj=on&ani=off&sd=off&fi=on&fc=on&plrg=&plrgt=1.5&hmb=off&heb=off&asea=off&smh=off&zo=on&us=on&msi=10&ahs=off&whas=500&sm=on&a51=off&theme=BODY.bg_FFFFFF-SEARCH.bg_FFFFFF.placeHolder_bbbbbb.bottomLine_858585-LOGO.text_888888.logoTextDividingLine_cccccc&bit=0&sit=0&sgit=0&sbit=0&pit=0&mit=0&lcit=0&zn=Y&fullpath=%2Fmain')

In [ ]:
driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/ul/li').get_attribute('data-sido')

### KT 데이터 매칭

In [3]:
DF = pd.read_excel('./test.xlsx')
DF

,법정동코드,법정동명,점포명,상세주소
0,4111513400,경기도 수원시 팔달구 매산로1가,AK수원점,경기도 수원시 팔달구 매산로1가 18번지 외 11필지 수원민자역사 제1호
1,4161025900,경기도 광주시 곤지암읍,BGF곤지암포켓점,경기도 광주시 곤지암읍 건업리 148번지
2,4146311800,경기도 용인시 기흥구 보정동,BGF로지스용인점,경기도 용인시 기흥구 보정동 319번지 1층
3,1168010500,서울특별시 강남구 삼성동,BGF사옥점,서울특별시 강남구 삼성동 141-10번지
4,4163025000,경기도 양주시 백석읍,BGF양주포켓점,경기도 양주시 백석읍 복지리 153번지 2층
...,...,...,...,...
16097,1130510400,서울특별시 강북구 우이동,419사거리점,서울특별시 강북구 우이동 72-144번지
16098,1156011000,서울특별시 영등포구 여의도동,63빌딩점,서울특별시 영등포구 여의도동 60번지 하
16099,2817710400,인천광역시 미추홀구 도화동,6공단1호점,인천광역시 미추홀구 도화동 84-5번지
16100,2817700000,인천광역시 남구 도화동,6공단2호점,인천광역시 남구 도화동 53-77번지
16101,4793038000,경상북도 울진군 후포면,7번국도점,경상북도 울진군 후포면 후포리 917-18번지

In [ ]:
DF = DF.rename(columns={'상세주소':'lgdng_nm_list'})

In [6]:
df_kt = pd.read_csv('./KT_data/dp_frc_bldg_ftc_pred_slng_m_sum_202205.csv',sep='|')

In [8]:
df_code = pd.read_csv('./0. 법정동코드.csv')
df_code = df_code.rename(columns={'법정동명':'lgdng_nm_list'})

In [17]:
df = pd.merge(DF, df_code, on='lgdng_nm_list', how='left')
df[df['법정동코드'].isnull()].index

KeyError: '법정동코드'

In [14]:
df_kt[df_kt['rn'].str.contains('가정로', na=False)]

,base_ym,bd_mgt_sn,sido_cd,sido_nm,sig_cd,sig_nm,emd_cd,emd_nm,rn_cd,rn,buld_mnnm,buld_slno,ftc_cate2_cd,pred_slng_amt
5073,202205,1123010400100460037026343,11,서울특별시,11230,동대문구,11230104,전농동,4115169,사가정로13길,18,3,A13,11679975.18
5074,202205,1123010400100460037026343,11,서울특별시,11230,동대문구,11230104,전농동,4115169,사가정로13길,18,3,B11,6769732.33
5075,202205,1123010400100460037026343,11,서울특별시,11230,동대문구,11230104,전농동,4115169,사가정로13길,18,3,B15,7372936.21
5076,202205,1123010400100460037026343,11,서울특별시,11230,동대문구,11230104,전농동,4115169,사가정로13길,18,3,A05,32596009.87
5077,202205,1123010400100460037026343,11,서울특별시,11230,동대문구,11230104,전농동,4115169,사가정로13길,18,3,C03,10265521.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58768379,202205,2826010900102880003005043,28,인천광역시,28260,서구,28260109,신현동,4268043,가정로351번길,17,0,C04,3190585.72
58768380,202205,2826010900102880003005043,28,인천광역시,28260,서구,28260109,신현동,4268043,가정로351번길,17,0,B10,100만원 미만
58768381,202205,2826010900102880003005043,28,인천광역시,28260,서구,28260109,신현동,4268043,가정로351번길,17,0,B04,1737368.24
58768382,202205,2826010900102880003005043,28,인천광역시,28260,서구,28260109,신현동,4268043,가정로351번길,17,0,B13,100만원 미만
58768383,202205,2826010900102880003005043,28,인천광역시,28260,서구,28260109,신현동,4268043,가정로351번길,17,0,B12,4274578.21

In [10]:
df_kt['lgdng_nm_list'] = df_kt['sido_nm'] + ' ' + df_kt['sig_nm'] + ' ' + df_kt['lgdng_nm_list']

,base_ym,bd_mgt_sn,sido_cd,sido_nm,sig_cd,sig_nm,emd_cd,emd_nm,rn_cd,rn,buld_mnnm,buld_slno,ftc_cate2_cd,pred_slng_amt
0,202205,1156010300100940250033726,11,서울특별시,11560,영등포구,11560103,영등포동2가,4154412,버드나루로12나길,28,0,C01,4587401.19
1,202205,1156010300100940250033726,11,서울특별시,11560,영등포구,11560103,영등포동2가,4154412,버드나루로12나길,28,0,A04,32468842.46
2,202205,1156010300100940250033726,11,서울특별시,11560,영등포구,11560103,영등포동2가,4154412,버드나루로12나길,28,0,A10,34027600.28
3,202205,1156010300100940250033726,11,서울특별시,11560,영등포구,11560103,영등포동2가,4154412,버드나루로12나길,28,0,A11,43316766.15
4,202205,1156010300100940250033726,11,서울특별시,11560,영등포구,11560103,영등포동2가,4154412,버드나루로12나길,28,0,B10,5470478.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58776136,202205,4812725028100390000060848,48,경상남도,48127,창원시 마산회원구,48127250,내서읍,4790115,삼계2길,24,0,B08,100만원 미만
58776137,202205,4812725028100390000060848,48,경상남도,48127,창원시 마산회원구,48127250,내서읍,4790115,삼계2길,24,0,B12,10266674.83
58776138,202205,4812725028100390000060848,48,경상남도,48127,창원시 마산회원구,48127250,내서읍,4790115,삼계2길,24,0,A15,10473593.25
58776139,202205,4812725028100390000060848,48,경상남도,48127,창원시 마산회원구,48127250,내서읍,4790115,삼계2길,24,0,A14,15105307.10
58776140,202205,4812725028100390000060848,48,경상남도,48127,창원시 마산회원구,48127250,내서읍,4790115,삼계2길,24,0,A04,9006663.15

### 카카오맵 api (위경도 -> 행정동코드로 변환)

In [ ]:
import pandas as pd
import requests 
import sys
import json
import datetime

In [ ]:
def json_request(url='', encoding='utf-8', success=None, error=lambda e: print('%s : %s' % (e, datetime.now()), file=sys.stderr)):
    headers = {'Authorization': 'KakaoAK {}'.format(APP_KEY)}
    resp = requests.get(url, headers=headers)
    return resp.text


def reverse_geocode(longitude, latitude):
    # 파라미터 최적화하여 url 생성
    url = '%s?x=%s&y=%s' %(URL, longitude, latitude)
    # json request
    try:
        json_req  = json_request(url=url)
        json_data = json.loads(json_req)
        json_doc  = json_data.get('documents')[0]
        json_name = json_doc.get('address_name')
        json_code = json_doc.get('code')
    except:
        json_name = 'NaN'
        json_code = 'NaN'
    return json_name, json_code


def get_address(x,y):
    address = []        
    json_name, json_code = reverse_geocode(x, y) 
    address.append(json_name)
    return address # 전처리 함수에서 주소 리스트 받아서 데이터프레임에 추가


def get_code(x,y):
    code = []        
    json_name, json_code = reverse_geocode(x, y) 
    code.append(json_code)
    return code # 전처리 함수에서 행정구역코드 리스트 받아서 데이터프레임에 추가

In [ ]:
APP_KEY = '' 
URL = 'https://dapi.kakao.com/v2/local/geo/coord2regioncode.json'

df_all = pd.read_csv('./서울특별시_병의원_위치_정보.csv', encoding='cp949') 
df = df_all[['기관ID', '병원경도', '병원위도']]


for i in range(len(df)): 
    x_crd = float(df.loc[i, ['병원경도']])
    y_crd = float(df.loc[i, ['병원위도']])
    address = get_address(x_crd, y_crd)
    code  = get_code(x_crd, y_crd)
    df.loc[i, ['ADDRESS']] = address
    df.loc[i, ['CODE']] = code
    
    if i%100 == 0:
        print('{} 번째 경위도 좌표계에 대한 정보 불러오는 중...'.format(i))