In [1]:
### 0. 임포트
import datetime
import numpy  as np
import pandas as pd
from selenium import webdriver # version_3.14.1

# 압축 풀기
import os
import glob
import zipfile

# shp 파일, 폴리곤 변환
import fiona
from pyproj import Proj, transform
from shapely.geometry import Point, Polygon

# DB 연동
import time
import psycopg2

# 경고 처리
import warnings
warnings.filterwarnings('ignore')

PROJ: proj_create_from_database: Cannot find proj.db

### 최종

In [2]:
### 0. 임포트
import datetime
import numpy  as np
import pandas as pd
from selenium import webdriver # version_3.14.1

# 압축 풀기
import os
import glob
import zipfile

# shp 파일, 폴리곤 변환
import fiona
from pyproj import Proj, transform
from shapely.geometry import Point, Polygon

# DB 연동
import time
import psycopg2

# 경고 처리
import warnings
warnings.filterwarnings('ignore')



### 1. 파일 다운로드
# 페이지 열기
driver = webdriver.Chrome('./driver/chromedriver.exe')
driver.get('https://www.data.go.kr/data/15086933/fileData.do')
driver.maximize_window()

# 최신 파일인지 확인 후 다운로드
dir = 'C:\\Users\\duPar\\Downloads\\'
downloadDate = datetime.datetime.fromtimestamp(os.path.getctime(glob.glob(dir + '한국부동산원*.zip')[0])).strftime('%Y%m') # 파일 다운로드 날짜

from datetime import datetime # 임포트 순서 바꾸면 안됨 (오늘 날짜)
today = datetime.now().strftime("%Y%m")
if today > downloadDate:
    
    # 다운로드
    downBtn = driver.find_element_by_xpath('//*[@id="contents"]/div[2]/div[1]/div[3]/div/a[1]').click()
    
    # 다운로드 완료되면 창 닫기
    while True:
        if len(glob.glob(dir + '한국부동산원*.zip')) > 0:
            driver.close()
            break



### 2. shp 파일 읽기
# 압축 풀기
zipfile.ZipFile(glob.glob(dir + '한국부동산원*.zip')[0]).extractall(os.getcwd())

# 좌표 매칭
proj_UTMK  = Proj(init = 'epsg:5179')
proj_WGS84 = Proj(init = 'epsg:4326')
proj_GRS80 = Proj(init = 'epsg:5181')

# 파일 가져오기
shape = fiona.open(glob.glob('./market_area*.shp')[0])

# 변수 생성
ID   = []
poly = []
sido = []
district_name = []

for j in range(len(shape)):
    
    # 폴리곤 변환
    if shape[j]['geometry']['type'] == 'Polygon':
        new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][0][0][0],shape[j]['geometry']['coordinates'][0][0][1])
        a = str(new[1]) + ' ' + str(new[0])
        for i in range(1,len(shape[j]['geometry']['coordinates'][0])): 
            new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][0][i][0],shape[j]['geometry']['coordinates'][0][i][1])
            b = str(new[1]) + ' ' + str(new[0])
            a = a + ',' + b
        
        # 컬럼명 수집
        X = 'MultiPolygon(((' + a + ')))' # id
        CNAME = shape[j]['properties']['CNAME'] # 상권명 (CNAME = district_name)
        sido_ = shape[j]['properties']['SIDOCODE'] # 시도코드
        
        # 리스트에 담기
        ID.append(j)
        poly.append(X)
        sido.append(sido_)
        district_name.append(CNAME)
        
    # 멀티 폴리곤인 경우, 변환 없이 바로 값 담기
    else:
        X = ''
        # 멀티 폴리곤 값 추출
        for k in range(len(shape[j]['geometry']['coordinates'])):
            if len(X) > 0:
                X = X + ','
            new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][k][0][0][0],shape[j]['geometry']['coordinates'][0][0][0][1])
            a = str(new[1]) + ' ' + str(new[0])
            for l in range(1,len(shape[j]['geometry']['coordinates'][k][0])):
                new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][k][0][l][0],shape[j]['geometry']['coordinates'][k][0][l][1])
                b = str(new[1]) + ' ' + str(new[0])
                a = a + ',' + b
            Y = '(' + a +')'
            X = X + Y
            
        # 컬럼명 수집
        Z = 'MultiPolygon((' + X + '))' # id
        CNAME = shape[j]['properties']['CNAME'] # 상권명
        sido_ = shape[j]['properties']['SIDOCODE'] # 시도코드
        
        # 리스트에 담기
        ID.append(j)
        poly.append(Z)
        sido.append(sido_)
        district_name.append(CNAME)

# 데이터프레임화
df = pd.DataFrame(data = zip(ID,poly,district_name,sido),columns = ['id','polygon_area','district_name','sido'])
df = df.drop(columns=['id'])



### 4. DB 연동
import datetime # 순서 바꾸면 안됨
table = 'm1.polygon_area' # 테이블 지정

# execute_mogrify
def execute_mogrify(conn, df, table, val):
    # Create a list of tuples from the dataframe values
    tuples = [tuple(x) for x in df.to_numpy()]
    # Comma-separated dataframe columns
    cols = ','.join(list(df.columns))
    # SQL query to execute
    cursor = conn.cursor()
    # drop & create
    cursor.execute(
    """
    drop table if exists m1.polygon_area;
    create table m1.polygon_area (
    polygon_area geography
    , district_name varchar(200)
    , sido varchar(5)
    )
    compound sortkey(district_name, sido);
    commit;
    """
    )
    values = [cursor.mogrify(val, tup).decode('utf8') for tup in
              tuples]
    query = "INSERT INTO %s(%s) VALUES " % (table, cols) + ",".join(values)

    try:
        cursor.execute(query, tuples)
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        conn.rollback()
        cursor.close()
        return 1
    cursor.close()

# values 설정
val = '(ST_GeomFromText(%s, 4326),%s,%s)'

# polygon str 변환
df['polygon_area'] = df['polygon_area'].astype(str)

# insert
for j in range(0, len(df), 10000):

    # DB Connect
    conn = psycopg2.connect(
        host='redshift-cluster-1.ctvbwnnvbdkl.ap-northeast-2.redshift.amazonaws.com',
        port=5439,
        dbname='dev',
        user='awsuser',
        password='cremaoAdmin1234qwer!!'
    )

    # 10000개 단위로 나누기
    tmp = df[j:j + 10000]

    # insert
    execute_mogrify(conn, tmp, table, val)
    print(datetime.datetime.now(), ' : ', j)
    tmp = pd.DataFrame()

# row count
print(len(df))

2022-10-05 17:18:05.256241  :  0
312

test

In [2]:
### 2. shp 파일 읽기
# 압축 풀기
dir = 'C:\\Users\\duPar\\Downloads\\'
# zipfile.ZipFile(glob.glob(dir + '한국부동산원*.zip')[0]).extractall(os.getcwd())

# 좌표 매칭
proj_UTMK  = Proj(init = 'epsg:5179')
proj_WGS84 = Proj(init = 'epsg:4326')
proj_GRS80 = Proj(init = 'epsg:5181')

# 파일 가져오기
shape = fiona.open(glob.glob('./market_area*.shp')[0])

In [4]:
# 변수 생성
ID   = []
poly = []
sido = []
district_name = []

for j in range(len(shape)):
    
    # 폴리곤 변환
    if shape[j]['geometry']['type'] == 'Polygon':
        new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][0][0][0],shape[j]['geometry']['coordinates'][0][0][1])
        a = str(new[1]) + ' ' + str(new[0])
        for i in range(1,len(shape[j]['geometry']['coordinates'][0])): 
            new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][0][i][0],shape[j]['geometry']['coordinates'][0][i][1])
            b = str(new[1]) + ' ' + str(new[0])
            a = a + ',' + b
        
        # 컬럼명 수집
        X = 'MultiPolygon(((' + a + ')))' # id
        CNAME = shape[j]['properties']['CNAME'] # 상권명 (CNAME = district_name)
        sido_ = shape[j]['properties']['SIDOCODE'] # 시도코드
        
        # 리스트에 담기
        ID.append(j)
        poly.append(X)
        sido.append(sido_)
        district_name.append(CNAME)
        
    # 멀티 폴리곤인 경우, 변환 없이 바로 값 담기
    else:
        X = ''
        # 멀티 폴리곤 값 추출
        for k in range(len(shape[j]['geometry']['coordinates'])):
            if len(X) > 0:
                X = X + ','
            new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][k][0][0][0],shape[j]['geometry']['coordinates'][0][0][0][1])
            a = str(new[1]) + ' ' + str(new[0])
            for l in range(1,len(shape[j]['geometry']['coordinates'][k][0])):
                new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][k][0][l][0],shape[j]['geometry']['coordinates'][k][0][l][1])
                b = str(new[1]) + ' ' + str(new[0])
                a = a + ',' + b
            Y = '(' + a +')'
            X = X + Y
            
        # 컬럼명 수집
        Z = 'MultiPolygon((' + X + '))' # id
        CNAME = shape[j]['properties']['CNAME'] # 상권명
        sido_ = shape[j]['properties']['SIDOCODE'] # 시도코드
        
        # 리스트에 담기
        ID.append(j)
        poly.append(Z)
        sido.append(sido_)
        district_name.append(CNAME)

# 데이터프레임화
df = pd.DataFrame(data = zip(poly,district_name,sido),columns = ['polygon_area','district_name','sido'])

In [5]:
idx = df[df['district_name']=='경북도청신도시'].index
df['polygon_area'][idx] = df['polygon_area'][idx].astype(str)

In [8]:
name_list = ['신정동', '동대구', '나주구시가지', '광양읍', '경북도청신도시', '계명대']
idx_list = []
for i in name_list:
    idx = df[df['district_name']==i].index
    idx_list.append(idx)

In [9]:
idx_list

[Int64Index([137], dtype='int64'),
 Int64Index([29], dtype='int64'),
 Int64Index([103], dtype='int64'),
 Int64Index([223], dtype='int64'),
 Int64Index([283], dtype='int64'),
 Int64Index([27], dtype='int64')]

In [56]:
df['polygon_area'][29].split(')')[2]

'22.2152235377012 121.17533400707812,(22.215327732617194 121.17800474809103,22.23337525606234 121.17774618901025,22.231869171820588 121.17912203058926,22.23115871513567 121.17977103087861,22.229919484351697 121.18090303919713,22.229636539418454 121.18064772680667,22.22710037115189 121.17835928580914,22.22708115418552 121.17832078074989,22.226900411128085 121.17795730367997,22.22687759583765 121.17790719639171,22.226767595557487 121.17765886978947,22.226692982525385 121.17743177002897,22.226683563247548 121.17740310066229,22.22663737938778 121.1772625328913,22.226625899630534 121.17722760125464,22.226581757010713 121.17709324461997,22.226576109980048 121.17707434383193,22.226562681166882 121.17702955197034,22.226299542869434 121.17643655776922,22.226256791017533 121.17628237752722,22.226272700397253 121.17625908330525,22.226040335014186 121.17534637972565,22.225550792870223 121.17396282227716,22.22439883106891 121.1739443516577,22.224040983321107 121.1739937851941,22.222882140558337 121.17399125897094,22.222020136037123 121.17404098687652,22.22171979528998 121.17405831649818,22.2209349703197 121.1741275962394,22.220700132263648 121.17415185431494,22.219861003969346 121.17423852055579,22.21918625735866 121.17435577897284,22.21862494926477 121.17446178113036,22.218272890245405 121.17454535535653,22.2182087692626 121.1745586648355,22.21785105009503 121.17463291671756,22.217766116868457 121.17465053644432,22.21736564316113 121.1747336571467,22.21649357846853 121.17490715585447,22.216457941950473 121.17503777490641,22.216380643983715 121.17532112223978,22.216303700692137 121.17560317726074,22.216227440294418 121.1760791684662,22.215997435101155 121.17591875337006,22.215905053388553 121.17585431898969,22.215221893062854 121.17540068379671,22.215222841520536 121.17536249851783,22.215223542931756 121.17533414112036,22.215249799427067 121.17531336349629,22.215248604878024 121.17531177211848,22.21525885838045 121.17530267434,22.215258411427325 121.17529246520091,22.2152484586059 121.17528273704535,22.214945729693707 121.1751138592732,22.213982395065667 121.17530576110188,22.214081166085123 121.17429808123921,22.21315093765027 121.17437576796367,22.21294430807973 121.17052895831178,22.214387389842805 121.17041509317802,22.215038271086172 121.17028786373277,22.215420271469096 121.17050612512644,22.21544502074226 121.16954329402749,22.21544573617592 121.16953049873723,22.216244727302563 121.16944110747099,22.216466197695365 121.1694630382635,22.216727267036273 121.16948889320314,22.216957381571405 121.16951167970105,22.2174681045518 121.16956224798014,22.217787120090314 121.16959169587363,22.218112097265653 121.1696216933344,22.218272070405558 121.16963646001999,22.21828328865072 121.16963749539863,22.21884465159241 121.16968931058813,22.219050704862248 121.16970833433402,22.21917136783192 121.16971947680024,22.219188505344366 121.16972105984009,22.21940060913799 121.16974062916148,22.2194150627763 121.16974196313352,22.219895510851195 121.16978632204597,22.22026117778652 121.16982007137032,22.22083532074636 121.16987306054318,22.220931413177503 121.16988193464262,22.22103173826395 121.16989119281497,22.22116841189202 121.16989081988862,22.221601322233315 121.16989289017296,22.221761034095422 121.16985733240749,22.222172406961853 121.16977284306755,22.222195117064306 121.16976068861855,22.222200187392104 121.16975955975168,22.222746761631953 121.16947028267828,22.222875521162326 121.16939954134999,22.22301135866675 121.16932385144356,22.223889190409217 121.16885404392492,22.2239037621068 121.16884624489018,22.224590171078205 121.16842269995313,22.224368271633544 121.16762995666106,22.224728254642844 121.1675067998025,22.225410861602924 121.16730286149571,22.225436242532236 121.1672952790805,22.225417231945446 121.16729624059472,22.225382482682612 121.16720288167303,22.225317843455684 121.16695742713503,22.22526885554498 121.16681363255763,22.22518113778185 121.16660441368269,22.22511108846855 121.16640792739268,22.224998320097516 121.16613543780336,22.224994066889245 121.16612516307214,22.224976466498614 121.16608046977558,22.224948016033196 121.16599694530028,22.224947597430795 121.16599571696648,22.224943527602118 121.16598378294096,22.22479722209108 121.16559874926944,22.22469476418064 121.16529798661851,22.224648395301323 121.1651877374725,22.22487206592367 121.16468639755216,22.22495463496967 121.16489983541877,22.22514988796477 121.16540599946808,22.225231259169096 121.16561734768192,22.225491021449315 121.16630236048664,22.225573723608804 121.16650880308154,22.225996137148638 121.16633016458576,22.226229350242274 121.16623153769262,22.22637473075574 121.1661845907817,22.226448820551706 121.1663648649598,22.22662405298033 121.1662467579277,22.226856980571203 121.16610963448501,22.227282570386276 121.16593072814017,22.22728673753053 121.16588972833524,22.227700552149575 121.16564544902452,22.227909679268436 121.16553074370977,22.22821514014345 121.16538037135784,22.228773173596746 121.16518225251419,22.228920370030657 121.1651327207795,22.229120340571086 121.16507977046896,22.229896772735067 121.16489199627303,22.229942712868386 121.16503553266615,22.229945504367944 121.16504426117513,22.229966244671207 121.16510906191306,22.229969933257166 121.16512058163919,22.230009486364235 121.16524416043531,22.230016799673844 121.16526701632712,22.230131146216408 121.16562429178242,22.230173168710788 121.16575559379646,22.23018135178057 121.16578116492377,22.23021672703472 121.16589169393501,22.230219872633292 121.1659008760477,22.23028128874796 121.16608021806105,22.230322710283673 121.16620117334085,22.23036984703051 121.16636466617824,22.230385757657867 121.1664198520916,22.230420714362783 121.16652907197691,22.230427880533576 121.16655145837896,22.230539772206402 121.16690108443892,22.230566068497286 121.16698324769854,22.23056701952737 121.16698622297096,22.230576856023625 121.16701695705817,22.230612756230368 121.16712912975092,22.230614908695866 121.16713584866841,22.230797239810343 121.16770555995744,22.230834092658434 121.16782071411114,22.2308355311654 121.16782520741813,22.230844862513205 121.16785436646464,22.23084572399043 121.16785705305468,22.23088349128941 121.16794189637395,22.230941854431226 121.16807298401011,22.231026479883628 121.16826308396728,22.231027907483085 121.16826690728672,22.23141074626418 121.16946040508883,22.231420003541544 121.16948926343119,22.23161202852131 121.16973887713498,22.231758851655954 121.16995515828081,22.23188860096676 121.17014030301098,22.23223900374487 121.17056332182192,22.232592648284548 121.17102701423029,22.232592677149963 121.171027752994,22.232757924984526 121.1712452326187,22.23276626147906 121.1712552960122,22.233022357456328 121.1716292120199,22.23302759082341 121.17170282060097,22.232972318018163 121.17186661392886,22.233235144006304 121.17212352746806,22.23345007952353 121.17233362917405,22.233865649658682 121.17338927974252,22.233861912951845 121.17364648288637,22.233899926742467 121.17358489919538,22.233899709299543 121.1736406358363,22.233845191266326 121.1739126313609,22.233895276026423 121.17477560850173,22.23389410926358 121.17507408072879,22.233896290836327 121.17512386704874,22.233866016360743 121.17527332830836,22.23386635209804 121.17542064727601,22.23386406278123 121.17557395007071,22.233864077858133 121.17570732740043,22.23387069312014 121.17592407475365,22.233951812132087 121.17639094756527,22.233970166509714 121.17680985133096,22.234160428752418 121.17697879360101,22.234121586507783 121.17704317924726,22.234093089876744 121.17709041524463,22.234012919092052 121.17716365525649'

In [77]:
df['polygon_area'][103]

'MultiPolygon(((21.305717097803313 119.55298864903332,21.305710244337785 119.55297839276511,21.3057137462548 119.55297962961349,21.305717097803313 119.55298864903332),(21.306258379134572 119.5643834278794,21.2976546134971 119.56451801809406,21.298028723790917 119.56136612147131,21.298162044528116 119.560242754572,21.2981773287257 119.56011396401232,21.298510701406 119.55730463122491,21.298512474055325 119.55728968980301,21.29877776190547 119.55737696305059,21.298905936579224 119.55741913029426,21.29903445845067 119.55746141090556,21.2984247739832 119.55488219016006,21.298877208996473 119.55444979135244,21.298877468067644 119.55444933411485,21.299348831365887 119.55361544606245,21.299416302435873 119.55349608170084,21.299659913717576 119.55306510055327,21.2999612638913 119.5529423687226,21.300222097661717 119.55283613644835,21.30048684319419 119.55272831057411,21.30049753700877 119.55272395533127,21.30053433737038 119.55270896661582,21.302470888234296 119.55124884118632,21.302490344390947 119.55123417130085,21.302734797827497 119.55039244665195,21.30310851190014 119.5504774455076,21.304049992713438 119.5508180924738,21.30412203253539 119.55085637786513,21.304231626258083 119.55091462521834,21.305017042249208 119.55197770677836,21.3056743628679 119.55296571866576,21.3057096476021 119.55297818190708,21.30604035987147 119.55408459002727,21.306084956000575 119.55513084572262,21.306147438802657 119.5565969788659,21.30628771758613 119.55988967200514,21.306376117141365 119.56196542199136,21.306377270182463 119.56199250131283,21.30620224314782 119.56214187520291,21.305055291324596 119.56312070317048,21.305049346524836 119.563125777726,21.302834362799842 119.56510248546228,21.302700103821532 119.56510104062933,21.30138947717859 119.56508693165382,21.300327400834874 119.56470518655289,21.30032445555642 119.5647041280071)))'

In [53]:
df['polygon_area'][29] = df['polygon_area'][29][:315] + ')'+ df['polygon_area'][29][316:]

In [45]:
df['polygon_area'][29] =  df['polygon_area'][29][:315] + ',22.2152235377012 121.17533400707812' + df['polygon_area'][29][315:]

In [ ]:
# 나주구시가지
idx = 103
df['polygon_area'][idx] = df['polygon_area'][idx][:-3] + ',22.91568376990522 120.99387993499913)))'

In [ ]:
# 동대구
idx = 29
df['polygon_area'][idx] =  df['polygon_area'][idx][:315] + ',22.2152235377012 121.17533400707812' + df['polygon_area'][idx][315:]
df['polygon_area'][idx] = df['polygon_area'][idx][:-3] + ',22.215327732617194 121.17800474809103)))'

In [ ]:
# 경북도청신도시
idx = 283
df['polygon_area'][idx] = df['polygon_area'][idx][:-3] + ',22.91568376990522 120.99387993499913)))'

In [21]:
# 신정동
idx = 29
df['polygon_area'][idx] = df['polygon_area'][idx][:-3] + ',22.2152235377012 121.17533400707812)))'

In [20]:
### 4. DB 연동
import datetime # 순서 바꾸면 안됨
table = 'm1.polygon_area' # 테이블 지정

# execute_mogrify
def execute_mogrify(conn, df, table, val):
    # Create a list of tuples from the dataframe values
    tuples = [tuple(x) for x in df.to_numpy()]
    # Comma-separated dataframe columns
    cols = ','.join(list(df.columns))
    # SQL query to execute
    cursor = conn.cursor()

    values = [cursor.mogrify(val, tup).decode('utf8') for tup in
              tuples]
    query = f"UPDATE m1.polygon_area SET polygon_area = {df['polygon_area'][283]} where district_name = '경북도청신도시'"

    try:
        cursor.execute(query, tuples)
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        conn.rollback()
        cursor.close()
        return 1
    cursor.close()

# values 설정
val = '(ST_GeomFromText(%s, 4326))'

# polygon str 변환
df['polygon_area'] = df['polygon_area'].astype(str)

# insert
for j in range(0, len(df), 10000):

    # DB Connect
    conn = psycopg2.connect(
        host='redshift-cluster-1.ctvbwnnvbdkl.ap-northeast-2.redshift.amazonaws.com',
        port=5439,
        dbname='dev',
        user='awsuser',
        password='cremaoAdmin1234qwer!!'
    )

    # 10000개 단위로 나누기
    tmp = df[j:j + 10000]

    # insert
    execute_mogrify(conn, tmp, table, val)
    print(datetime.datetime.now(), ' : ', j)
    tmp = pd.DataFrame()

# row count
print(len(df))

TypeError: not all arguments converted during string formatting

### test

In [15]:
### 3. shp 파일 읽기
import glob
import fiona
from pyproj import Proj, transform
from shapely.geometry import Point, Polygon

# 좌표 매칭
proj_UTMK = Proj(init = 'epsg:5179')
proj_WGS84 = Proj(init = 'epsg:4326')
proj_GRS80 = Proj(init = 'epsg:5181')

# 파일 가져오기
shape = fiona.open(glob.glob('./market_area*.shp')[0])

# 폴리곤 변환
ID = []
poly = []
sido = []
district_name = []
for j in range(len(shape)):    
    if shape[j]['geometry']['type'] == 'Polygon':
        # 폴리곤 변환
        new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][0][0][0],shape[j]['geometry']['coordinates'][0][0][1])
        a = str(new[1]) + ' ' + str(new[0])
        for i in range(1,len(shape[j]['geometry']['coordinates'][0])): 
            new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][0][i][0],shape[j]['geometry']['coordinates'][0][i][1])
            b = str(new[1]) + ' ' + str(new[0])
            a = a + ',' + b
        
        # id 수집
        X = 'MultiPolygon(((' + a + ')))'
        
        # 상권명 (CNAME = district_name) 수집
        CNAME = shape[j]['properties']['CNAME']
        
        # 시도코드 수집
        sido_ = shape[j]['properties']['SIDOCODE']
        
        # 리스트에 담기
        ID.append(j)
        poly.append(X)
        sido.append(sido_)
        district_name.append(CNAME)
    else:
        X = ''    
        for k in range(len(shape[j]['geometry']['coordinates'])):
            if len(X) > 0:
                X = X + ','
            new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][k][0][0][0],shape[j]['geometry']['coordinates'][0][0][0][1])
            a = str(new[1]) + ' ' + str(new[0])
            for l in range(1,len(shape[j]['geometry']['coordinates'][k][0])):
                new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][k][0][l][0],shape[j]['geometry']['coordinates'][k][0][l][1])
                b = str(new[1]) + ' ' + str(new[0])
                a = a + ',' + b
            Y = '(' + a +')'
            X = X + Y
        Z = 'MultiPolygon((' + X + '))'
        ID.append(j)
        poly.append(Z)
        
df = pd.DataFrame(data = zip(ID,poly,district_name,sido),columns = ['id','polygon_area','district_name','sido'])
df = df.drop(columns=['id'])
df.to_csv('./polygonfile.csv',index=False,encoding='utf-8-sig')

C:\Users\duPar\Anaconda3\envs\oasis\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\duPar\Anaconda3\envs\oasis\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\duPar\Anaconda3\envs\oasis\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\duPar\AppData\Local\Temp\ipykernel_7512\728388672.py:49: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][k][0][0][0],shape[j]['geometry']['coordinates'][0][0][0][1])
C:\Users\duPar\AppData\Local\Temp\ipykernel_7512\728388672.py:52: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][k][0][l][0],shape[j]['geometry']['coordinates'][k][0][l][1])
C:\Users\duPar\AppData\Local\Temp\ipykernel_7512\728388672.py:23: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][0][0][0],shape[j]['geometry']['coordinates'][0][0][1])
C:\Users\duPar\AppData\Local\Temp\ipykernel_7512\728388672.py:26: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][0][i][0],shape[j]['geometry']['coordinates'][0][i][1])

In [16]:
# 폴리곤 형식 변환 후 12개가 사라짐 (변환 후 폴리곤 개수 300개)
df1 = pd.read_csv('./polygonfile.csv')

In [17]:
df1

                                           plogon_area district_name  sido
0    MultiPolygon(((23.770983454051592 119.68782817...          건대입구    11
1    MultiPolygon(((23.816446175027387 119.72322867...           경희대    11
2    MultiPolygon(((23.85979059229518 119.704500392...           공덕역    11
3    MultiPolygon(((23.813273956601044 119.62525262...           동대문    11
4    MultiPolygon(((23.83976662033341 119.680915121...            명동    11
..                                                 ...           ...   ...
295  MultiPolygon(((22.11799852871642 119.808614797...          평촌범계    41
296  MultiPolygon(((23.776099205214415 119.33668264...           여의도    11
297  MultiPolygon(((23.747508069006805 119.30217861...        강경젓갈시장    44
298  MultiPolygon(((23.889978130858502 119.35294343...        송정해수욕장    26
299  MultiPolygon(((23.56084726068309 119.734018724...           울산대    31

[300 rows x 3 columns]

In [7]:
# 부동산원이 제공한 상권 폴리곤 개수 (312개)
shape = fiona.open(glob.glob('./market_area*.shp')[0])

In [6]:
len(shape)

312

###### 폴리곤 12개 실종사건 (해결)

In [11]:
### 3. shp 파일 읽기
import glob
import fiona
from pyproj import Proj, transform
from shapely.geometry import Point, Polygon

# 좌표 매칭
proj_UTMK = Proj(init = 'epsg:5179')
proj_WGS84 = Proj(init = 'epsg:4326')
proj_GRS80 = Proj(init = 'epsg:5181')

# 파일 가져오기
shape = fiona.open(glob.glob('./market_area*.shp')[0])

# 폴리곤 변환
ID = []
poly = []
sido = []
district_name = []
for j in range(len(shape)):    
    if shape[j]['geometry']['type'] == 'Polygon':
        # 폴리곤 변환
        new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][0][0][0],shape[j]['geometry']['coordinates'][0][0][1])
        a = str(new[1]) + ' ' + str(new[0])
        for i in range(1,len(shape[j]['geometry']['coordinates'][0])): 
            new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][0][i][0],shape[j]['geometry']['coordinates'][0][i][1])
            b = str(new[1]) + ' ' + str(new[0])
            a = a + ',' + b
        
        # id 수집
        X = 'MultiPolygon(((' + a + ')))'
        
        # 상권명 (CNAME = district_name) 수집
        CNAME = shape[j]['properties']['CNAME']
        
        # 시도코드 수집
        sido_ = shape[j]['properties']['SIDOCODE']
        
        # 리스트에 담기
        ID.append(j)
        poly.append(X)
        sido.append(sido_)
        district_name.append(CNAME)
    else:
        X = ''    
        for k in range(len(shape[j]['geometry']['coordinates'])):
            if len(X) > 0:
                X = X + ','
            new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][k][0][0][0],shape[j]['geometry']['coordinates'][0][0][0][1])
            a = str(new[1]) + ' ' + str(new[0])
            for l in range(1,len(shape[j]['geometry']['coordinates'][k][0])):
                new = transform(proj_UTMK, proj_WGS84, shape[j]['geometry']['coordinates'][k][0][l][0],shape[j]['geometry']['coordinates'][k][0][l][1])
                b = str(new[1]) + ' ' + str(new[0])
                a = a + ',' + b
            Y = '(' + a +')'
            X = X + Y
            
        # 컬럼명 수집
        Z = 'MultiPolygon((' + X + '))' # id 수집
        CNAME = shape[j]['properties']['CNAME'] # 상권명 (CNAME = district_name) 수집
        sido_ = shape[j]['properties']['SIDOCODE'] # 시도코드 수집
        
        # 리스트에 담기
        ID.append(j)
        poly.append(Z)
        sido.append(sido_)
        district_name.append(CNAME)
        
df = pd.DataFrame(data = zip(ID,poly,district_name,sido),columns = ['id','polygon_area','district_name','sido'])
df = df.drop(columns=['id'])
df.to_csv('./polygonfile.csv',index=False,encoding='utf-8-sig')

In [12]:
# 폴리곤 형식 변환 후 개수 ()
df1 = pd.read_csv('./polygonfile.csv')
df1

                                          polygon_area district_name  sido
0    MultiPolygon(((23.770983454051592 119.68782817...          강남대로    11
1    MultiPolygon(((23.816446175027387 119.72322867...          건대입구    11
2    MultiPolygon(((23.85979059229518 119.704500392...           경희대    11
3    MultiPolygon(((23.813273956601044 119.62525262...           공덕역    11
4    MultiPolygon(((23.83976662033341 119.680915121...           동대문    11
..                                                 ...           ...   ...
307  MultiPolygon(((23.66205467389693 119.638979155...          평촌범계    41
308  MultiPolygon(((23.79399287203476 119.587491921...           여의도    11
309  MultiPolygon(((22.436562502396015 119.76089495...        강경젓갈시장    44
310  MultiPolygon(((21.567372604166795 121.71859003...        송정해수욕장    26
311  MultiPolygon(((21.920520681451464 121.73934605...           울산대    31

[312 rows x 3 columns]

### 압축 풀기 되는 거

- 여러 개 풀기

In [43]:
import os
import zipfile
with zipfile.ZipFile(dir + '한국부동산원_상업용부동산 임대동향조사_전국 17개시도 상권 구획도_20210831.zip', 'r') as zip_ref:
    zip_ref.extractall(os.getcwd())

- 한 개 풀기

In [41]:
import os
import zipfile
dir = 'C:\\Users\\duPar\\Downloads\\'
zipfile.ZipFile(dir + '한국부동산원_상업용부동산 임대동향조사_전국 17개시도 상권 구획도_20210831.zip').extractall(os.getcwd())

### DB 연동

In [2]:
df = pd.read_csv('./polygonfile.csv')

In [3]:
df

                                          polygon_area district_name  sido
0    MultiPolygon(((23.770983454051592 119.68782817...          건대입구    11
1    MultiPolygon(((23.816446175027387 119.72322867...           경희대    11
2    MultiPolygon(((23.85979059229518 119.704500392...           공덕역    11
3    MultiPolygon(((23.813273956601044 119.62525262...           동대문    11
4    MultiPolygon(((23.83976662033341 119.680915121...            명동    11
..                                                 ...           ...   ...
295  MultiPolygon(((22.11799852871642 119.808614797...          평촌범계    41
296  MultiPolygon(((23.776099205214415 119.33668264...           여의도    11
297  MultiPolygon(((23.747508069006805 119.30217861...        강경젓갈시장    44
298  MultiPolygon(((23.889978130858502 119.35294343...        송정해수욕장    26
299  MultiPolygon(((23.56084726068309 119.734018724...           울산대    31

[300 rows x 3 columns]

In [4]:
### 4. DB 연동
# 임포트
import time
import zipfile
import psycopg2
import datetime
from tqdm import tqdm
from glob import glob

# 테이블
table = 'm1.polygon_area'

# execute_mogrify
def execute_mogrify(conn, df, table, val):
    # Create a list of tuples from the dataframe values
    tuples = [tuple(x) for x in df.to_numpy()]
    # Comma-separated dataframe columns
    cols = ','.join(list(df.columns))
    # SQL query to execute
    cursor = conn.cursor()
    # drop & create
    cursor.execute(
    """
    drop table if exists m1.polygon_area;
    create table m1.polygon_area (
    polygon_area super
    , district_name varchar(200)
    , sido varchar(5)
    )
    compound sortkey(district_name, sido);
    commit;
    """
    )
    values = [cursor.mogrify(val, tup).decode('utf8') for tup in
              tuples]
    query = "INSERT INTO %s(%s) VALUES " % (table, cols) + ",".join(values)

    try:
        cursor.execute(query, tuples)
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        conn.rollback()
        cursor.close()
        return 1
    cursor.close()

# values 설정
val = '(' + ('%s,' * len(df.columns))[:-1] + ')'

# insert
for j in range(0, len(df), 10000):

    # DB Connect
    conn = psycopg2.connect(
        host='redshift-cluster-1.ctvbwnnvbdkl.ap-northeast-2.redshift.amazonaws.com',
        port=5439,
        dbname='dev',
        user='awsuser',
        password='cremaoAdmin1234qwer!!'
    )

    # 10000개 단위로 나누기
    tmp = df[j:j + 10000]

    # insert
    execute_mogrify(conn, tmp, table, val)
    print(datetime.datetime.now(), ' : ', j)
    tmp = pd.DataFrame()

# row count
print(len(df))

2022-09-20 14:16:36.157299  :  0
300